### ISSUE TITLE
the problem in top_n functin

### ISSUE THREAD

**Issue by justicevita** [clhchtcjj/BiNE#10]
I find that the code in line 180 of train.py
`        tmp_t = sorted(test_rate[u].items(), lambda x, y: cmp(x[1], y[1]), reverse=True)[0:min(len(test_rate[u]),len(test_rate[u]))]
`
you use 
`min(len(test_rate[u]),len(test_rate[u]))`
but they are the same.

**Comment by clhchtcjj** [comment]
You're right, thank you!

**Comment by justicevita** [comment]
> You're right, thank you!

Do we need to make any change on the code?
like this?
`min(len(test_rate[u]),top_n)
`
