### ISSUE TITLE
networkx.exception.NetworkXError:HITS: power iteration failed to converge in 102 iterations.

### ISSUE THREAD

**Issue by WangHexie** [clhchtcjj/BiNE#3]
Is [this](https://stackoverflow.com/questions/43208737/using-networkx-to-calculate-eigenvector-centrality?rq=1) the reason? And how to solve in this case?It seems it cannot simply solved by replacing a function.
```
Traceback (most recent call last):
  File "D:/programming/BiNE/model/train.py", line 572, in <module>
    sys.exit(main())
  File "D:/programming/BiNE/model/train.py", line 569, in main
    train_by_sampling(args)
  File "D:/programming/BiNE/model/train.py", line 321, in train_by_sampling
    walk_generator(gul,args)
  File "D:/programming/BiNE/model/train.py", line 55, in walk_generator
    gul.calculate_centrality()
  File "D:\programming\BiNE\model\graph_utils.py", line 61, in calculate_centrality
    h, a = nx.hits(self.G)
  File "D:\Anaconda3.5\envs\BiNE\lib\site-packages\networkx\algorithms\link_analysis\hits_alg.py", line 111, in hits
    "HITS: power iteration failed to converge in %d iterations."%(i+1))
networkx.exception.NetworkXError: HITS: power iteration failed to converge in 102 iterations.

```

**Comment by WangHexie** [comment]
[https://stackoverflow.com/questions/43208737/using-networkx-to-calculate-eigenvector-centrality?rq=1](https://stackoverflow.com/questions/43208737/using-networkx-to-calculate-eigenvector-centrality?rq=1)

**Comment by clhchtcjj** [comment]
In your training/testing data, each line is an instance and should be written in this format: userID (begin with 'u')\titemID (begin with 'i') \tweight\n.
If you had written your training data in this way,  you can try to expand the value of "max_iter" in the **nx.hits(self.G, max_iter=500)**.

**Comment by WangHexie** [comment]
Solved, thanks a lot.

**Comment by munirasyed** [comment]
I'm having the same issue. I changed the number of iterations to 1000, keeping the learning rate at 0.01 but it still gives me the same error. Any idea what parameters I might have to change to solve this?

**Comment by eduOS** [comment]
@munirasyed Most probably the graph is empty because you didn't follow the data format as the author had stated in this issue: userID (**begin with 'u'**)\titemID (**begin with 'i'**) \tweight\n. Pay special attention to the words in bold.

**Comment by oushnik23** [comment]
PowerIterationFailedConvergence           Traceback (most recent call last)
[<ipython-input-119-609ef3f19cf2>](https://localhost:8080/#) in <cell line: 1>()
----> 1 katz_Centrality=nx.katz_centrality(g1,alpha=0.1, beta=1.0, max_iter=1000, tol=1.0e-3)

2 frames
[/usr/local/lib/python3.10/dist-packages/networkx/algorithms/centrality/katz.py](https://localhost:8080/#) in katz_centrality(G, alpha, beta, max_iter, tol, nstart, normalized, weight)
    192                 x[n] *= s
    193             return x
--> 194     raise nx.PowerIterationFailedConvergence(max_iter)
    195 
    196 

PowerIterationFailedConvergence: (PowerIterationFailedConvergence(...), 'power iteration failed to converge within 1000 iterations')
